In [1]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5, 1) # 5행 1열
t_data = np.array([2, 3, 4, 5, 6]).reshape(5, 1)
# print("x_data.shape = ", x_data.shape, ", y_data.shape = ", t_data.shape) # .shape : 차원을 튜플로 리턴

In [2]:
# 데이터가 리스트로 들어온다면
raw_data = [[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]

raw_data = np.array(raw_data)
print(type(raw_data))
print(raw_data[:, :1])
print(raw_data[:, -1:])
print(raw_data[:, :1].shape)
print(raw_data[:, -1:].shape)

# raw_data_x = []
# raw_data_t = []
# for i in range(0, len(raw_data)):
#     raw_data_x.append(raw_data[i][0])
#     raw_data_t.append(raw_data[i][1])
# x_data = np.array(raw_data_x).reshape(5, 1)
# t_data = np.array(raw_data_t).reshape(5, 1)

<class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
(5, 1)
(5, 1)


In [3]:
W = np.random.rand(1, 1) # 1행 1열
b = np.random.rand(1) # 값 하나
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)
print(W.ndim, b.ndim) # 2차원, 1차원

# 왜 W를 2차원으로 만들까
# W*x가 가능해야 하기 때문에(x : 5행 1열)

W =  [[0.20034067]] , W.shape =  (1, 1) , b =  [0.55556988] , b.shape =  (1,)
2 1


In [4]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t-y)**2))/(len(x))

In [5]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001(미세하게 변하는 x값)
    grad = np.zeros_like(x) # x와 같은 모양을 만듦, 값은 모두 0
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) # iterator
    
    while not it.finished:
        idx = it.multi_index # 위치값을 가져와서 idx에 저장
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x + delta_x)
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) # f(x - delta_x)
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [6]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t-y)**2))/(len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x, W) + b
    return y

In [7]:
learning_rate = 1e-2 # 발산하는 경우, 1e-3~1e-6 등으로 바꾸어서 실행
f = lambda x: loss_func(x_data, t_data)
print("Initial error value = ", error_val(x_data, t_data), ", Initial W = ", W, ", Initial b = ", b)

for step in range(8001): # 8000번 반복
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    if(step%400 == 0): # 400번마다 1번씩 결과 출력하도록
        print("step = ", step, ", error value = ", error_val(x_data, t_data), ", W = ", W, ", b = ", b)

Initial error value =  9.36387978819072 , Initial W =  [[0.20034067]] , Initial b =  [0.55556988]
step =  0 , error value =  5.513124331291385 , W =  [[0.40293153]] , b =  [0.60028259]
step =  400 , error value =  0.0007575825280827903 , W =  [[1.01787359]] , b =  [0.93548647]
step =  800 , error value =  4.833824409900734e-05 , W =  [[1.00451484]] , b =  [0.98370399]
step =  1200 , error value =  3.0842657479026947e-06 , W =  [[1.00114044]] , b =  [0.99588366]
step =  1600 , error value =  1.9679438881150085e-07 , W =  [[1.00028807]] , b =  [0.99896022]
step =  2000 , error value =  1.2556645449213785e-08 , W =  [[1.00007277]] , b =  [0.99973735]
step =  2400 , error value =  8.011882142131825e-10 , W =  [[1.00001838]] , b =  [0.99993366]
step =  2800 , error value =  5.1120544669990955e-11 , W =  [[1.00000464]] , b =  [0.99998324]
step =  3200 , error value =  3.2617929735886187e-12 , W =  [[1.00000117]] , b =  [0.99999577]
step =  3600 , error value =  2.0812167563328992e-13 , W =  

In [8]:
predict(43)

array([[44.]])