In [1]:
import numpy as np

loaded_data = np.loadtxt('./data-01.csv', delimiter = ',', dtype = np.float32)
print(type(loaded_data)) # ndarray type
print(loaded_data)

<class 'numpy.ndarray'>
[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [2]:
x_data = loaded_data[:, 0:-1] # : : slicing
t_data = loaded_data[:, [-1]] # [-1] : fancy indexing

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape", t_data.shape)

x_data.ndim =  2 , x_data.shape (25, 3)
t_data.ndim =  2 , t_data.shape (25, 1)


In [3]:
W = np.random.rand(3, 1) # 3행 1열
b = np.random.rand(1) # 값 하나
print("W = ", W.tolist(), ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.7673161891393098], [0.8124044258358518], [0.4282890288915022]] , W.shape =  (3, 1) , b =  [0.28651573] , b.shape =  (1,)


In [4]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t-y)**2))/(len(x))

In [5]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001(미세하게 변하는 x값)
    grad = np.zeros_like(x) # x와 같은 모양을 만듦, 값은 모두 0
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) # iterator
    
    while not it.finished:
        idx = it.multi_index # 위치값을 가져와서 idx에 저장
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x + delta_x)
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) # f(x - delta_x)
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [6]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t-y)**2))/(len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x, W) + b
    return y

In [7]:
learning_rate = 1e-5
f=lambda x: loss_func(x_data, t_data)
print("Initial error value = ", error_val(x_data, t_data), '\n', "Initial W = ", W.tolist(), '\n', "Initial b = ", b)

for step in range(1000001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    if(step%10000 == 0):
        print("step = ", step, '\n', "error value = ", error_val(x_data, t_data), '\n', "W = ", W.tolist(), '\n', "b = ", b)

Initial error value =  22.966400046189296 
 Initial W =  [[0.7673161891393098], [0.8124044258358518], [0.4282890288915022]] 
 Initial b =  [0.28651573]
step =  0 
 error value =  21.25833960702307 
 W =  [[0.76982771412108], [0.814871819335426], [0.431258772668193]] 
 b =  [0.28653576]
step =  10000 
 error value =  6.168152798641015 
 W =  [[0.3882379730436636], [0.5184738725841583], [1.1040373883372196]] 
 b =  [0.27413364]
step =  20000 
 error value =  6.144672263560936 
 W =  [[0.3586132516793462], [0.5283064514536785], [1.1234311720348957]] 
 b =  [0.2565952]
step =  30000 
 error value =  6.141420268043576 
 W =  [[0.3562025940969041], [0.5295643346170769], [1.1247574591434069]] 
 b =  [0.23893257]
step =  40000 
 error value =  6.138318470493781 
 W =  [[0.3560045814540639], [0.5297178013951839], [1.1250119486156598]] 
 b =  [0.22132489]
step =  50000 
 error value =  6.135241348377362 
 W =  [[0.35598813890782494], [0.5297756413542677], [1.1251826211953675]] 
 b =  [0.20378394

In [9]:
predict(10)

array([[ 2.41022432],
       [ 4.18624938],
       [10.22830921]])