### Numpy ndarray 개요

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 type 형태 : ', array1.shape)
print(array1.ndim) # 차원

array1 type :  <class 'numpy.ndarray'>
array1 type 형태 :  (3,)
1


In [3]:
array2 = np.array([[1,2,3],[2,3,4]])
print('array1 type : ', type(array2))
print('array1 type 형태 : ', array2.shape)
print(array2.ndim) # 차원

array1 type :  <class 'numpy.ndarray'>
array1 type 형태 :  (2, 3)
2


In [4]:
array3 = np.array([[1,2,3]])
print('array1 type : ', type(array3))
print('array1 type 형태 : ', array3.shape)
print(array3.ndim) # 차원

array1 type :  <class 'numpy.ndarray'>
array1 type 형태 :  (1, 3)
2


#### ndarray의 데이터 타입 : 한 종류로(여러 종류가 섞이면 안 된다)

In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_int.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_int.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### ndarray 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print((one_array.dtype, one_array.shape))

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(dtype('float64'), (3, 2))


#### ndarray의 차원과 크기를 변환하는 reshape()

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array1:\n', array2)

array3 = array1.reshape(5,2)
print('array1:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array1:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array1:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1 = np.arange(15)
print(array1)
array2 = array1.reshape(-1, 5)
print('array1 shape : ', array2.shape)
array3 = array1.reshape(5, -1)
print('array1 shape : ', array3.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
array1 shape :  (3, 5)
array1 shape :  (5, 3)


#### tolist() : 리스트 자료형으로 변경

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)
print('array3d : \n', array3d.tolist())
result = array3d.tolist()
print(type(result))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
<class 'list'>


#### 데이터 세트 선택하기 - 인덱싱, 슬라이싱

In [15]:
array1 = np.arange(start=1,stop=10) # 1부터 9까지
print('array1 : ', array1)

value = array1[2]
print('value : ', value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [20]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0,1], array2d[1,0], array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2 4 9


In [21]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3] # 0에서 2까지
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [24]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print()
print('array2d[0:2,0:2]')
print(array2d[0:2,0:2])
print('array2d[1:3,:]')
print(array2d[1:3,:])
print('array2d[:2,1:]')
print(array2d[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2,0:2]
[[1 2]
 [4 5]]
array2d[1:3,:]
[[4 5 6]
 [7 8 9]]
array2d[:2,1:]
[[2 3]
 [5 6]]


#### fancy indexing

In [25]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2] # 3 6
print(array3.tolist())

[3, 6]


#### boolean indexing

In [28]:
array1d = np.arange(start=1,stop=10)
array3 = array1d[array1d>5]
print(array1d>5)
print(array3)

[False False False False False  True  True  True  True]
[6 7 8 9]


#### 행렬 정렬

In [30]:
org_array = np.array([3,1,9,5])
print(np.max(org_array)) # 가장 큰 값
print(np.argmax(org_array)) # 가장 큰 값이 들어있는 곳의 인덱스

9
2


In [35]:
org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array) # 원본 변경 X, 내림차순 : np.sort(org_array)[::-1]
print('원본 : ', org_array)
print('정렬 : ', sort_array1)
sort_array2 = org_array.sort() # 원본 변경
print('원본 : ', org_array)
print('정렬 : ', sort_array2)

[3 1 9 5]
원본 :  [3 1 9 5]
정렬 :  [1 3 5 9]
원본 :  [1 3 5 9]
정렬 :  None


In [37]:
array2d = np.array([[8, 12],
                    [7, 1]])
print(array2d)
sort_array2d_axis0 = np.sort(array2d, axis=0) # 행 방향 정렬(상, 하)
print(sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1) # 열 방향 정렬(좌, 우)
print(sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [38]:
array2d = np.array([[8, 12],
                    [7, 1]])
print(np.max(array2d, axis=0))
print(np.max(array2d, axis=1))
print(np.argmax(array2d, axis=0))
print(np.argmax(array2d, axis=1))

[ 8 12]
[12  7]
[0 0]
[1 0]


In [39]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [41]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)[::-1]
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


#### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [42]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7, 8],
             [9, 10],
             [11, 12]])
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [43]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 브로드캐스트 : 크기가 다른 두 행렬 간 사칙연산 가능

In [44]:
a = np.array([[1, 2], [3, 4]])
b = 5
a + b

array([[6, 7],
       [8, 9]])

In [46]:
c = np.array([[1, 2], [3, 4]])
d = np.array([4, 5])
c + d

array([[5, 7],
       [7, 9]])

In [49]:
e = np.array([[1, 2], [3, 4]])
f = np.array([[4], [5]])
e + f

array([[5, 6],
       [8, 9]])

#### iterator : 명시적인 인덱싱이나 슬라이싱 이외에 행렬의 모든 원소를 Access할 때 사용

In [50]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [51]:
a.shape

(2, 4)

In [53]:
iter = np.nditer(a, flags=['multi_index'], op_flags=['readwrite'])

In [54]:
while not iter.finished:
    idx = iter.multi_index
    print('current value : ', a[idx])
    iter.iternext()

current value :  10
current value :  20
current value :  30
current value :  40
current value :  50
current value :  60
current value :  70
current value :  80


#### concatenate : 행렬에 행 또는 열 추가, 
#### 머신러닝의 회귀(regresstion) 코드 구현 시 가중치(weight)와 바이어스(bias)를 별도로 구분하지 않고
#### 하나의 행렬로 취급하기 위한 프로그램이 구현 기술

In [56]:
a = np.array([[10,20,30],[50,60,70]])
a

array([[10, 20, 30],
       [50, 60, 70]])

In [57]:
a.shape

(2, 3)

In [58]:
type(a)

numpy.ndarray

In [59]:
row_add = np.array([70,80,90]).reshape(1,3) # 3행에 붙기 위해 1행 3열짜리로
col_add = np.array([1000,2000]).reshape(2,1) # 4열에 붙기 위해 2행 1열짜리로

In [60]:
b = np.concatenate((a, row_add), axis=0)
b

array([[10, 20, 30],
       [50, 60, 70],
       [70, 80, 90]])

In [61]:
c = np.concatenate((a, col_add), axis=1)
c

array([[  10,   20,   30, 1000],
       [  50,   60,   70, 2000]])