In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [3]:
encoder = LabelEncoder()

In [4]:
encoder.fit(items)

LabelEncoder()

In [5]:
labels = encoder.transform(items)

In [6]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [7]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [8]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [10]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [11]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [12]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [13]:
# 원-핫 인코딩 : 입력 값으로 2차원 데이터가 필요하므로 변환
labels = labels.reshape(-1, 1)

In [14]:
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

In [15]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels) # labels : 숫자, 2차원
oh_labels = oh_encoder.transform(labels)

In [16]:
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [17]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])